function Hd = blackman300
%BLACKMAN300 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 19-Apr-2025 11:12:22

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in kHz.
Fs = 32;  % Sampling Frequency

N    = 300;      % Order
Fc   = 14.5;     % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = blackman(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);
end
% [EOF]
