function Hd = equiripple270
    %EQUIRIPPLE270 Returns a discrete-time filter object.
    
    % MATLAB Code
    % Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
    % Generated on: 19-Apr-2025 11:46:35
    
    % Equiripple Lowpass filter designed using the FIRPM function.
    
    % All frequency values are in kHz.
    Fs = 32;  % Sampling Frequency
    
    N     = 270;   % Order
    Fpass = 14;    % Passband Frequency
    Fstop = 14.7;  % Stopband Frequency
    Wpass = 1;     % Passband Weight
    Wstop = 1;     % Stopband Weight
    dens  = 20;    % Density Factor
    
    % Calculate the coefficients using the FIRPM function.
    b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
               {dens});
    Hd = dfilt.dffir(b);
end
% [EOF]
