function Hd = han250
%HAN250 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 19-Apr-2025 11:24:47

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in kHz.
Fs = 32;  % Sampling Frequency

N    = 250;      % Order
Fc   = 14.2;     % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hann(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
